name: Deploy Angular

on:
  push:
    branches: ["master","main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build React
        run: npm run build

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

      - name: Add known hosts
        run: |
          ssh-keyscan -H "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts

      - name: Create target folder on VPS
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          "mkdir -p /var/www/html/brandonviz.dev/"

      - name: Deploy build via rsync
        run: |
          rsync -avz --delete \
            dist/browser/ \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/html/brandonviz.dev/
      - name: Fix permissions
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            chown -R www-data:www-data /var/www/html/brandonviz.dev &&
            chmod -R 755 /var/www/html/brandonviz.dev
          "